
name: Release on npmjs.org
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - run: git config --global user.email dev@chronark.com
      - run: git config --global user.name chronark


      - run: yarn install
      - run: yarn build
      - run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > .npmrc
      - run: yarn release